### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by laheller** [libmtp/libmtp#101]
Hi @msmeissn 

Is it possible to use exclusively only **libmtp** to remote control **DSLR cameras**, like adjust camera settings, take photos, download photos, etc? I am asking, because I see that this library includes also _ptp.h/ptp.c_ which is a PTP protocol implementation. Yes, I know, that there is libgphoto2, but that one also includes the same header/source files.

BR,

Ladislav

**Comment by msmeissn** [comment]
please use libgphoto2.

the intelligence lies largely in other files in libgphoto2 (library.c, config.c of the ptp2 driver). the ptp.c and ptp.h are the lowlevel wrappers around the functionality.

**Comment by HT-7** [comment]
A side advise: If you ask something in any online forum, the title should be more descriptive, meaning it should contain the essential part of the question.
