### ISSUE TITLE
Add link to http://libmtp.sourceforge.net to the About block here on GitHub

### ISSUE THREAD

**Issue by cher-nov** [libmtp/libmtp#104]
this would be convenient :)

**Comment by msmeissn** [comment]
its in README already.

Why do you need it here?

**Comment by cher-nov** [comment]
> its in README already.
Yep, but it's not a first one there, and with a lot of text around.

> Why do you need it here?
Just for easier browser navigation.

**Comment by msmeissn** [comment]
i added a link now.
