### ISSUE TITLE
Device 0 (VID=1782 and PID=4003) is UNKNOWN in libmtp v1.1.17.

### ISSUE THREAD

**Issue by kiki78** [libmtp/libmtp#109]
My new tablet Alldocube Smile X is not recognize by libmtp.
Device 0 (VID=1782 and PID=4003) is UNKNOWN in libmtp v1.1.17.
Android version 11
lsusb report : Bus 001 Device 006: ID 1782:4003 Spreadtrum Communications Inc. Unisoc Phone
OS : Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-13-amd64

Regards,

**Comment by msmeissn** [comment]
thx for the report!
