### ISSUE TITLE
Device 0 (VID=17ef and PID=7cb3) is UNKNOWN in libmtp v1.1.19

### ISSUE THREAD

**Issue by mpessel** [libmtp/libmtp#111]
Hi, 

Lenovo TAB M7 Gen 3 more specifically, the TB-7306F

Linux esox 5.18.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1 (2022-06-06) x86_64 GNU/Linux

> mtp-detect
libmtp version: 1.1.19

Listing raw device(s)
Device 0 (VID=17ef and PID=7cb3) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   17ef:7cb3 @ bus 1, dev 14
Attempting to connect device(s)
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP PANIC: Unable to initialize device
Unable to open raw device 0
OK.

> mtp-connect
Device 0 (VID=17ef and PID=7cb3) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP PANIC: Unable to initialize device
No devices.

**Comment by msmeissn** [comment]
thx for the reportm, will be in next release!
