### ISSUE TITLE
Please report this VID/PID and the device model to the libmtp development team (One Plus 7T Pro 5G McLaren T-Mobile Variant, rooted)

### ISSUE THREAD

**Issue by felingreenleaf** [libmtp/libmtp#112]
[user@computer /]$ jmtpfs
Device 0 (VID=2a70 and PID=9012) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
Android device detected, assigning default bug flags
fuse: missing mountpoint parameter

**Comment by felingreenleaf** [comment]
Output of lsusb 

> lsusb
Bus 002 Device 002: ID 0bda:0316 Realtek Semiconductor Corp. Card Reader
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04f2:b5ab Chicony Electronics Co., Ltd Integrated Camera
Bus 001 Device 005: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 009: ID 1b1c:1b8b Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse
Bus 001 Device 012: ID 2a70:9012 OnePlus Technology (Shenzhen) Co., Ltd. SM8150P-MTP _SN:00EA35F8
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub


Output of lsusb  -vs 1:12
> Bus 001 Device 012: ID 2a70:9012 OnePlus Technology (Shenzhen) Co., Ltd. SM8150P-MTP _SN:00EA35F8
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x2a70 OnePlus Technology (Shenzhen) Co., Ltd.
  idProduct          0x9012 
  bcdDevice            4.14
  iManufacturer           1 OnePlus
  iProduct                2 SM8150P-MTP _SN:00EA35F8
  iSerial                 3 46403eb9
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003e
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          4 mtp_adb
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol      0 
      iInterface              5 MTP
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x001c  1x 28 bytes
        bInterval               6
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     66 
      bInterfaceProtocol      1 
      iInterface              6 ADB Interface
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0000
  (Bus Powered)

**Comment by msmeissn** [comment]
in git via commit ca1985cc, will be in next release... thanks for the report!
