### ISSUE TITLE
Device 0 (VID=0fce and PID=020a) is UNKNOWN in libmtp v1.1.18. Please report this VID/PID and the device model to the libmtp development team

### ISSUE THREAD

**Issue by gzqx** [libmtp/libmtp#113]
Device 0 (VID=0fce and PID=020a) is UNKNOWN in libmtp v1.1.18.
Please report this VID/PID and the device model to the libmtp development team

Sony Xperia 5

**Comment by msmeissn** [comment]
thx for the report!
