### ISSUE TITLE
Purpose of `LIBMTP_object_t`

### ISSUE THREAD

**Issue by cher-nov** [libmtp/libmtp#114]
https://github.com/libmtp/libmtp/blob/154756d2a2ba559ce8a006af5e519eb220c1cc0b/src/libmtp.h.in#L470

Is this used anywhere actually?

**Comment by msmeissn** [comment]
it was parts of refactoring in 2006... was removed at some later point in time, but not this define.

We could remove it from libmtp.h

**Comment by cher-nov** [comment]
https://github.com/libmtp/libmtp/commit/6909c75908ab00de668968e140eb3aa3b7c4d07c

> remvoed

uh oh

**Comment by msmeissn** [comment]
sorry ... my typing is not always good ;)
