### ISSUE TITLE
VID=2833 and PID=0183 is Oculus Quest 2

### ISSUE THREAD

**Issue by jayofdoom** [libmtp/libmtp#115]
Hi, received this message:

```
Device 0 (VID=2833 and PID=0183) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
```

This is the Oculus Quest 2, and MTP worked great on it.

Thanks for the good work!

**Comment by msmeissn** [comment]
The id is in the recent 1.1.20 release, commit c8a03c5f. thanks for the report! :)
