### ISSUE TITLE
Lenovo Tab TB-X306F is unknown

### ISSUE THREAD

**Issue by Philippe593** [libmtp/libmtp#116]
Hi,
I'm getting this while trying to connect my tab, using 1.1.20 :

Device 0 (VID=17ef and PID=7c97) is UNKNOWN in libmtp v1.1.20.
Please report this VID/PID and the device model to the libmtp development team
Available devices (busLocation, devNum, productId, vendorId, product, vendor):
1, 51, 0x7c97, 0x17ef, UNKNOWN, UNKNOWN

Could it be included in the next release ?
TIA

**Comment by msmeissn** [comment]
added the id to our id list, will be in next release :)

**Comment by Philippe593** [comment]
Thanks !
