### ISSUE TITLE
clarify github vs sourceforge

### ISSUE THREAD

**Issue by ari-s** [libmtp/libmtp#118]
Currently it's not very clear where libmtp's home is. The documentation mostly mentions sourceforge, but github seems to be more active - probably because today people are used to github. What's the project's stance here?
In particular, I have a patch for a new device. Where to I submit it? github pull request seems to be one way de facto, but sf is in the documentation. This should be clarified in the documentation.

**Comment by msmeissn** [comment]
I am currently working with bothm and keep the git repos in sync.

The plan is to move towards github.

You can submit this via github PR.
