### ISSUE TITLE
Library API implicitly assumes shared memory heap

### ISSUE THREAD

**Issue by cher-nov** [libmtp/libmtp#121]
Some of the libmtp API functions (`LIBMTP_Detect_Raw_Devices()`, `LIBMTP_Get_String_From_Object()`, etc) return dynamically allocated memory that must then be freed by the caller using the standard `free()` function from libc.

The problem is that such semantics implies that both the application and the library share the same memory allocator and access the same memory heap. Which is not really guaranteed and therefore not always true. Common examples are static linking with libc (possibly custom one, like musl) and usage of drop-in memory managers (see this, for instance: https://microsoft.github.io/mimalloc/overrides.html).

I believe this should either be explicitly stated somewhere in the documentation or fixed at the API level.

<details><summary></summary>

https://www.gnu.org/software/libc/manual/html_node/Replacing-malloc.html

https://stackoverflow.com/questions/7739323/freeing-memory-in-caller-or-callee
https://stackoverflow.com/questions/3296302/c-api-design-who-should-allocate

https://stackoverflow.com/questions/13625388/is-it-bad-practice-to-allocate-memory-in-a-dll-and-give-a-pointer-to-it-to-a-cli
https://stackoverflow.com/questions/26841004/how-to-free-memory-in-c-that-was-allocated-using-c-new-operator
https://stackoverflow.com/questions/64574662/allocating-and-deallocating-memory-across-shared-lib-boundaries
https://stackoverflow.com/questions/51232916/why-it-is-a-mistake-to-allocate-in-one-library-and-free-in-the-other
https://stackoverflow.com/questions/22406278/is-it-safe-to-free-memory-allocated-by-new

https://stackoverflow.com/questions/28227266/how-to-override-standard-libc-functions
https://stackoverflow.com/questions/8866790/do-shared-libraries-use-the-same-heap-as-the-application
https://stackoverflow.com/questions/23228705/are-libc-and-malloc-part-of-the-operating-system

</details>

**Comment by msmeissn** [comment]
should we specify then LIBMTP_*_free functions for those for consistency?

**Comment by cher-nov** [comment]
> should we specify then LIBMTP_*_free functions for those for consistency?

One common function `LIBMTP_FreeMemory()` for all these cases will be enough, I guess.

**Comment by msmeissn** [comment]
i added it.
