### ISSUE TITLE
Duplicated function description

### ISSUE THREAD

**Issue by cher-nov** [libmtp/libmtp#123]
https://github.com/libmtp/libmtp/blob/085a8ab8ce62d77cc4402c8ef42f761f50b1a4d8/src/libmtp.c#L2958-L2964

This is a copy of the description for the preceding function:

https://github.com/libmtp/libmtp/blob/085a8ab8ce62d77cc4402c8ef42f761f50b1a4d8/src/libmtp.c#L2930-L2936

**Comment by cher-nov** [comment]
Fixed in 08224127a6b270bf75fb4d025517e0bb9c1ec485, I guess?

**Comment by msmeissn** [comment]
ah yes, forgot to cross ref it.
