### ISSUE TITLE
cross compile for arm error

### ISSUE THREAD

**Issue by hyw0810** [libmtp/libmtp#131]
cross compile for arm error:

```
util/mtp-hotplug -w > 69-libmtp.hwdb
util/mtp-hotplug: line 117: libmtp/util/.libs/mtp-hotplug: cannot execute binary file: Exec format error
util/mtp-hotplug: line 117: libmtp/util/.libs/mtp-hotplug: Success
make[2]: *** [Makefile:970: 69-libmtp.hwdb] Error 126
```

what should I do?

**Comment by msmeissn** [comment]
yes, this is a piece which is currently not cross compile safe. need to figure out how to handle this correctly
you can buiuld with -k or similar to avoid this and then crearte the files on the target system

**Comment by msmeissn** [comment]
i think a fix is now in git for this
