### ISSUE TITLE
New device to be added GoPro HERO 11 Black (VID=2672 and PID=0059)

### ISSUE THREAD

**Issue by maxkapalla** [libmtp/libmtp#136]
Hi,

i dont see the GoPro Hero 11 Black in the Head version, so i guess the device is missing currently.

Here the output of mtp-detect

[goprohero11.txt](https://github.com/libmtp/libmtp/files/10105898/goprohero11.txt)

Thanks!

**Comment by msmeissn** [comment]
added, thanks!
