### ISSUE TITLE
Device 0 (VID=091e and PID=4f96) is UNKNOWN in libmtp v1.1.19.

### ISSUE THREAD

**Issue by ezfox** [libmtp/libmtp#150]
Device 0 (VID=091e and PID=4f96) is UNKNOWN in libmtp v1.
Please report this VID/PID and the device model to the libmtp development team

The device is a Garmin Forerunner 255M smartwatch.

$ mtp-detect
libmtp version: 1.1.19

Listing raw device(s)
Device 0 (VID=091e and PID=4f96) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   091e:4f96 @ bus 1, dev 22
Attempting to connect device(s)
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP PANIC: Unable to initialize device
Unable to open raw device 0
OK.

**Comment by msmeissn** [comment]
thx for the report!
