### ISSUE TITLE
Device 0 (VID=091e and PID=50db) is UNKNOWN in libmtp v1.1.19.

### ISSUE THREAD

**Issue by typhoon2099** [libmtp/libmtp#152]
Hey, I got a Garmin Forerunner 965, which doesn't seem to be supported.

Thanks!

EDIT: Output of `mtp-detect`:

```
libmtp version: 1.1.19

Listing raw device(s)
Device 0 (VID=091e and PID=50db) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   091e:50db @ bus 1, dev 24
Attempting to connect device(s)
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP PANIC: Unable to initialize device
Unable to open raw device 0
OK.
```

**Comment by msmeissn** [comment]
added to git

**Comment by pbiava** [comment]
Hey
I have an Epix Gen2 Pro watch.
I get the following message when I run `jmtpfs ~/mtp`:
Device 0 (VID=091e and PID=50da) is UNKNOWN in libmtp v1.1.21.
Please report this VID/PID and the device model to the libmtp development team

Thanks
