### ISSUE TITLE
question: is the winUSB driver required on windows for libmtp?

### ISSUE THREAD

**Issue by mpl** [libmtp/libmtp#159]
Hello,

At https://github.com/jabezwinston/mtp-tools , they explain how to replace the driver used by default for MTP when my phone is plugged in (WUDFWpdMtp), with winUSB, for the mtp-tools to work.
And that's what I seem to conclude as well when trying them out myself.
As I understand, these tools are built from the examples in libmtp/libmtp , correct?

However, I don't see any mention in the README here about windows driver, and in particular nothing about winUSB, so I'm a bit confused.
Do you confirm that libmtp can only communicate with an android phone plugged on windows if there's a winUSB driver installed, or could it work with the default one (e.g. WUDFWpdMtp)?

In addition, do you know how come a "native" windows app, like files explorer, can do MTP with my phone without the need for the winUSB driver to be installed?

Thank you for your time.

**Comment by msmeissn** [comment]
I think windows can natively browse MTP devices. (MTP was invented by Microsoft to a large degree)

Not exactly sure how Windows does these kind of things, but there probably is some form of Microsoft style virtual filesystem driver brought after device detection.

**Comment by mpl** [comment]
@msmeissn hmm ok, thanks.

Btw, please feel free to close this issue, as my main question is already answered.
It might be worth to make https://github.com/libmtp/libmtp/blob/master/README.windows.txt a little bit more discoverable (e.g. linked and highlighted from the main README), but that's just my 2 cents.

**Comment by cher-nov** [comment]
> But still, does anyone know how e.g. the windows files explorer does MTP?

Windows uses it's own, COM-based and more general API for this, called Windows Portable Devices (WPD).
https://stackoverflow.com/questions/16295774/winapi-calls-to-access-usb-storage-which-has-no-drive-letter
https://stackoverflow.com/questions/7912743/windows-mtp-wpd-communication-with-android-device

I had wrote a whole abstraction layer on top of it, maybe you'll find this interesting or even helpful:
https://github.com/cher-nov/plainmtp/blob/ae82211a/plainmtp/plainmtp_wpd.c

Here are some basic links to get you started:

https://learn.microsoft.com/en-us/windows/win32/windows-portable-devices
https://learn.microsoft.com/en-us/windows/win32/api/_wpdsdk/

https://learn.microsoft.com/en-us/archive/blogs/wpdblog/
https://learn.microsoft.com/en-us/archive/blogs/dimeby8/windows-portable-devices-wpd

https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/PortableDeviceCOM
https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/multimedia/wpd
https://github.com/microsoft/Windows-driver-samples/tree/main/wpd

**Comment by mpl** [comment]
@cher-nov ah, that's very interesting indeed, thank you!
So if you use the WPD API, you can talk MTP to your android without having to install any additional driver, right?

However, in the meantime, I found out that, using USB-tethering, one always has a network link between the two devices, so I'm simply going to use that plus e.g. HTTP on top of it to communicate between the two devices.
Seems much simpler and also easily portable to other OSes.

**Comment by cher-nov** [comment]
> So if you use the WPD API, you can talk MTP to your android without having to install any additional driver, right?

Yes. In addition, this is the only option if you want to interact with the device from several applications at once - WPD multiplexes access.
