### ISSUE TITLE
New device report

### ISSUE THREAD

**Issue by floe** [libmtp/libmtp#16]
```
$ mtp-detect 
libmtp version: 1.1.13

Listing raw device(s)
Device 0 (VID=1949 and PID=0271) is UNKNOWN in libmtp v1.1.13.
Please report this VID/PID and the device model to the libmtp development team
```

This is the Amazon Fire Tablet 7, I checked and it's not yet supported even in current master. Probably needs just the usual DEVICE_FLAGS_ANDROID_BUGS.

**Comment by msmeissn** [comment]
it is in 1.1.16 release, "Kindle Fire 7 (2nd ID)", commit 777e1a14
