### ISSUE TITLE
Vivo Y20i not listed

### ISSUE THREAD

**Issue by Hans-Pirante** [libmtp/libmtp#163]
mtp-detect
libmtp version: 1.1.19

Listing raw device(s)
Device 0 (VID=2d95 and PID=6003) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   2d95:6003 @ bus 1, dev 86

**Comment by msmeissn** [comment]
id was added in commit 3ab9ac0b, thanks for the report!
