### ISSUE TITLE
UNKNOWN device (VID=2a70 and PID=9012)

### ISSUE THREAD

**Issue by gsauer75** [libmtp/libmtp#167]
Device 0 (VID=2a70 and PID=9012) is UNKNOWN in libmtp v1.1.19.
Please report this VID/PID and the device model to the libmtp development team
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP

(VID=2a70 and PID=9012) = OnePlus 6
Bus 001 Device 016: ID 2a70:9012 OnePlus Technology (Shenzhen) Co., Ltd. OnePlus

Please at this smartphone. THX

**Comment by msmeissn** [comment]
this is listed in 1.1.20 and newer releases.

fixed by commit ca1985cc
