### ISSUE TITLE
Python pymtp and libmtp

### ISSUE THREAD

**Issue by fabio-ts** [libmtp/libmtp#204]
https://github.com/libmtp/libmtp/commit/286153a4659597095b99eafed60d579c4bead7fb

Hello! 

I have an issue with python3, pymtp and libmtp: I want to connect to a DJI android device with this simple code:
```
>>> import pymtp
>>> m = pymtp.MTP()
>>> m.connect()
```
The code fails with the error: "Device 0 (VID=2ca3 and PID=1021) is UNKNOWN in libmtp v1.1.19" which was fixed in this issue: https://github.com/libmtp/libmtp/issues/203

I cloned libmtp, checked the file 'src/music-players.h', and verified that the device was added and I installed the library correctly. Then I removed ed reinstalled pymtp library and rebooted the pc, but nothing worked for me, the connection fails with the same error. Is Anyhing else I can do? My pc runs Linux Mint 21.

Thanks!

**Comment by wreedamz** [comment]
can you share a link to pymtp? it sounds likely it is using an older version of libmtp

**Comment by fabio-ts** [comment]
Indeed you're right, it was written in Pyhton 2.7. Now I'm struggling to use libmtp in cython, but the LIBMTP_Get_Folder_List method crashes with segmentation fault error

**Comment by wreedamz** [comment]
you'll have to share more info to get help, but perhaps StackOverflow is a better place for that

**Comment by msmeissn** [comment]
i think this might solve it
