### ISSUE TITLE
Support Amazon Kindle Fire HD 8 2018 version

### ISSUE THREAD

**Issue by rfwgh** [libmtp/libmtp#21]
Here is information which should be helpful to add support for a new Amazon Kindle Fire HD 8  (2018 version).  I am attaching lsusb -v output (serial [number]( #url) obfuscated) as seen on Ubuntu Bionic LTS, and also my quick attempt at a libmtp patch, with which a build of jmtpfs is shown to be happier.

[lsusb-1949-0331.txt](https://github.com/libmtp/libmtp/files/2974084/lsusb-1949-0331.txt)
[git-show.txt](https://github.com/libmtp/libmtp/files/2974085/git-show.txt)

The Ubuntu Bionic version of jmtpfs says of this device:

jmtpfs-build# /usr/bin/jmtpfs -l
Device 0 (VID=1949 and PID=0331) is UNKNOWN in libmtp v1.1.13.
Please report this VID/PID and the device model to the libmtp development team
Available devices (busLocation, devNum, productId, vendorId, product, vendor):
2, 5, 0x0331, 0x1949, UNKNOWN, UNKNOWN

My newly built version, using libmtp to which the attached patch has been applied, says:

jmtpfs-build# ./src/jmtpfs -l
Device 0 (VID=1949 and PID=0331) is a Amazon Kindle Fire 8 HD (2018).
Available devices (busLocation, devNum, productId, vendorId, product, vendor):
2, 5, 0x0331, 0x1949, Kindle Fire 8 HD (2018), Amazon

**Comment by DzSolution** [comment]
Apr  6 03:25:21 z gvfsd[662]: Device 0 (VID=18d1 and PID=4e12) is UNKNOWN in libmtp v1.1.13.
Apr  6 03:25:21 z gvfsd[662]: Please report this VID/PID and the device model to the libmtp development team

Device 0 (VID=18d1 and PID=4e12) is a Nexus One.
Please help us.

**Comment by msmeissn** [comment]
Please stop spamming the bugtrackers. I have added the Nexus One id for the next release

**Comment by DzSolution** [comment]
Sorry thanks for your support!
