### ISSUE TITLE
Kindle Scribe is 'UNKNOWN'

### ISSUE THREAD

**Issue by tomsem** [libmtp/libmtp#214]
Would be nice to add this:

idVendor: 1949
idProduct: 9981
Manufacturer: Amazon
Model: Kindle Scribe

[scribe_info.txt](https://github.com/libmtp/libmtp/files/15325204/scribe_info.txt)

**Comment by msmeissn** [comment]
is in git, via https://github.com/libmtp/libmtp/issues/191 .. thanks for the report!

**Comment by tomsem** [comment]
Despite that PR being merged, it is still showing as UNKNOWN in latest release 1.1.21.
