### ISSUE TITLE
Device 0 (VID=1949 and PID=9981) is UNKNOWN in libmtp v1.1.21

### ISSUE THREAD

**Issue by tomhoats** [libmtp/libmtp#217]
Listing raw device(s)
   Found 1 device(s):
   1949:9981 @ bus 20, dev 2
Attempting to connect device(s)
USB low-level info:
   Interface has a kernel driver attached.
   bcdUSB: 512
   bDeviceClass: 0
   bDeviceSubClass: 0
   bDeviceProtocol: 0
   idVendor: 1949
   idProduct: 9981
   IN endpoint maxpacket: 512 bytes
   OUT endpoint maxpacket: 512 bytes
   Raw device info:
      Bus location: 20
      Device number: 2
      Device entry info:
         Vendor: (null)
         Vendor id: 0x1949
         Product: (null)
         Product id: 0x9981
         Device flags: 0x00000000
Configuration 0, interface 0, altsetting 0:
   Interface description contains the string "MTP"
   Device recognized as MTP, no further probing.
Device info:
   Manufacturer: Amazon
   Model: Kindle Scribe
   Device version: 
   Serial number: 
   Vendor extension ID: 0x00000006
   Vendor extension description: microsoft.com/WMDRMPD:10.1;microsoft.com/playready:1.10; 
   Detected object size: 64 bits
   Extensions:
        microsoft.com/WMDRMPD: 10.1
        microsoft.com/playready: 1.10
Supported operations:
   1001: Get device info
   1002: Open session
   1003: Close session
   1004: Get storage IDs
   1005: Get storage info
   1006: Get number of objects
   1007: Get object handles
   1008: Get object info
   1009: Get object
   100b: Delete object
   100c: Send object info
   100d: Send object
   1014: Get device property description
   1015: Get device property value
   1016: Set device property value
   101b: Get partial object
   9810: Get object references
   9811: Set object references
   9802: Get object property description
   9801: Get object properties supported
   9803: Get object property value
   9804: Set object property value
   9805: Get object property list
   9806: Set object property list
   1011: Self test device
   1017: Reset device property value
   1019: Move object
   101a: Copy object
   9808: Send object property list
   9202: Report Acquired Items
Events supported:
   0x4002: ObjectAdded
   0x4003: ObjectRemoved
   0x4004: StoreAdded
   0x4005: StoreRemoved
Device Properties Supported:
   0xd401: Synchronization Partner
   0xd402: Friendly Device Name
   0xd404: Unknown property
   0xd407: Perceived Device Type
   0xd405: Device Icon
Playable File (Object) Types and Object Properties Supported:
   b984: 3GP
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   b982: MP4
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3009: MP3
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   b901: WMA
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   b981: WMV
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3801: JPEG
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3001: Association/Directory
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   b906: FLAC
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3000: Undefined Type
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3004: Text
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3807: GIF
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3804: BMP
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   380b: PNG
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   3008: MS Wave
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   300a: MS AVI
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   300b: MPEG
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   300c: ASF
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
   ba03: Abstract Audio Album
      dc01: Storage ID UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc02: Object Format UINT16 data type ANY 16BIT VALUE form READ ONLY GROUP 0x8
      dc03: Protection Status UINT16 data type enumeration: 0, 1, 32770, 32771,  READ ONLY GROUP 0x8
      dc04: Object Size UINT64 data type READ ONLY GROUP 0x8
      dc07: Object File Name STRING data type GET/SET GROUP 0x8
      dc0b: Parent Object UINT32 data type ANY 32BIT VALUE form READ ONLY GROUP 0x8
      dc41: Persistant Unique Object Identifier UINT128 data type READ ONLY GROUP 0x8
      dc4f: Non Consumable UINT8 data type enumeration: 0, 1,  READ ONLY GROUP 0x8
      dc09: Date Modified STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc08: Date Created STRING data type DATETIME FORM ((null)) READ ONLY GROUP 0x8
      dc44: Name STRING data type READ ONLY GROUP 0x8
      dc05: Association Type UINT16 data type enumeration: 0, 1,  GET/SET GROUP 0x8
Storage Devices:
   StorageID: 0x00010001
      StorageType: 0x0003 fixed RAM storage
      FilesystemType: 0x0002 generic hierarchical
      AccessCapability: 0x0000 read/write
      MaxCapacity: 27929788416
      FreeSpaceInBytes: 27629871104
      FreeSpaceInObjects: 4294967295
      StorageDescription: Internal Storage
      VolumeIdentifier: -10001
Special directories:
   Default music folder: 0xffffffff
   Default playlist folder: 0xffffffff
   Default picture folder: 0xffffffff
   Default video folder: 0xffffffff
   Default organizer folder: 0xffffffff
   Default zencast folder: 0xffffffff
   Default album folder: 0xffffffff
   Default text folder: 0xffffffff
MTP-specific device properties:
   Friendly name: Kindle Scribe
   Synchronization partner: 
libmtp supported (playable) filetypes:
   MPEG-4 Part 14 Container Format (Audio+Video Emphasis)
   ISO MPEG-1 Audio Layer 3
   Microsoft Windows Media Audio
   Microsoft Windows Media Video
   JPEG file
   Folder
   Free Lossless Audio Codec (FLAC)
   Text file
   GIF bitmap file
   BMP bitmap file
   Portable Network Graphics
   RIFF WAVE file
   Audio Video Interleave
   MPEG video stream
   Microsoft Advanced Systems Format
   Abstract Album file

**Comment by msmeissn** [comment]
thanks for the report, was added with commit be085c17.
