### ISSUE TITLE
Unknown device, please report

### ISSUE THREAD

**Issue by tom-marshall** [libmtp/libmtp#222]
Hello,

I'm reporting a new device for the library.

Device 0 (VID=1949 and PID=9981) is UNKNOWN in libmtp v1.1.21.
Please report this VID/PID and the device model to the libmtp development team

The device is a Kindle Scribe, 32gb version:
https://www.amazon.com/gp/product/B09BSGFTHY/

Hope this helps :)

**Comment by msmeissn** [comment]
tahnks for the report. added via commit be085c17

**Comment by timboxyz** [comment]
The same VID and PID are also used for the 64G version, so maybe the commit shouldn't only list the 32G version
