### ISSUE TITLE
Device 0 (VID=09cb and PID=100b) is UNKNOWN in libmtp v1.1.17

### ISSUE THREAD

**Issue by SAlex24** [libmtp/libmtp#224]
I get this error when trying to connect to a FLIR C5 thermal camera:

Device 0 (VID=09cb and PID=100b) is UNKNOWN in libmtp v1.1.17.
Please report this VID/PID and the device model to the libmtp development team

Can this be fixed in a reasonable time?

**Comment by msmeissn** [comment]
added in commit c364dae7, is in libmtp 1.1.21
