### ISSUE TITLE
Device 0 (VID=339b and PID=107f) is UNKNOWN in libmtp v1.1.21.

### ISSUE THREAD

**Issue by oshitaka** [libmtp/libmtp#226]
Hi!  connecting device honor X8a, model CRT-LX1 to Arch Linux x86_64 with hyprland

Listing raw device(s)
Device 0 (VID=339b and PID=107f) is UNKNOWN in libmtp v1.1.21.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   339b:107f @ bus 1, dev 2
Attempting to connect device
PTP_ERROR_IO: failed to open session, trying again after resetting USB interface
LIBMTP libusb: Attempt to reset device

**Comment by pppanghu77** [comment]
https://github.com/libmtp/libmtp/issues/219 The latest version should have solved this problem

**Comment by msmeissn** [comment]
id is not yet in a release, but is in git commit 42202321

**Comment by oshitaka** [comment]
> id is not yet in a release, but is in git commit [4220232](https://github.com/libmtp/libmtp/commit/42202321ae901970a182676dd8b9ece0fa31fad6)

Thank you!
