### ISSUE TITLE
Printer HP LaserJet P1102 gets "mtp-probed" and this messes it up in CUPS

### ISSUE THREAD

**Issue by pezcurrel** [libmtp/libmtp#24]
After I installed libmtp-1.1.16 on my arch linux system, my printer, an HP LaserJet P1102 that I had previously configured and had worked well until that moment, stopped working. I saw in the journal that when I turned it on, it got "mtp-probed". Issuing "lpinfo -v" I got a different value for "serial" compared to the one configured in cups. In cups I had...

`usb://HP/LaserJet%20Professional%20P1102?serial=000000000Q87FWBPPR1a`

...but after libmtp installation, "lpinfo -v" gave...

`usb://HP/LaserJet%20Professional%20P1102?serial=000000000Q87FWBPSI1c`

mtp-probe shouldn't change this, or it shouldn't try and probe this printer at all.
As a workaround I added...

```
# HP LaserJet P1102
ATTR{idVendor}=="03f0", ATTR{idProduct}=="002a", GOTO="libmtp_rules_end"
```

...at the beginning of /usr/lib/udev/rules.d/69-libmtp.rules

**Comment by daissi** [comment]
Same bug affects people with Ubuntu.

https://bugs.launchpad.net/ubuntu/+source/libmtp/+bug/1863239

**Comment by tillkamppeter** [comment]
@msmeissn, thank you very much for applying my patch upstream, it will probably help many users.

**Comment by JoesCat** [comment]
reading the info, the applied patch would close https://sourceforge.net/p/libmtp/bugs/1697/
