### ISSUE TITLE
Unable to mount my Astel&Kern SR35

### ISSUE THREAD

**Issue by eliwap** [libmtp/libmtp#248]
Hi this is new

Device 0 (VID=4102 and PID=1247) is UNKNOWN in libmtp v1.1.22.

Thanks for looking into this

**Comment by eliwap** [comment]
K then found and implemented a work around.

I created:

`/etc/udev/rules.d/90-sr35.rules`

I added the following line:

`ATTR{idVendor}=="4102", ATTR{idProduct}=="1247", SYMLINK+="libmtp-%k", MODE="666", GROUP="disk", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"`


Then ran:

`systemctl reload systemd-udevd.service`


All seems to be well

**Comment by msmeissn** [comment]
i added the id to current git, so it will be in nexct distros
