### ISSUE TITLE
How to Mount MTP devices

### ISSUE THREAD

**Issue by Piju99** [libmtp/libmtp#32]
how I want to mount MTP device and see the files that have in device in terminal?

**Comment by internationils** [comment]
Have a look at https://github.com/JasonFerrara/jmtpfs
It hasn't been updated in a while but it works. Else there are several other MTP tools. Search for them.

**Comment by msmeissn** [comment]
also https://github.com/Feandil/mtpfs
and 
https://github.com/hanwen/go-mtpfs
