### ISSUE TITLE
Report VID/PID 

### ISSUE THREAD

**Issue by pavlinux** [libmtp/libmtp#42]
[lsusb.txt](https://github.com/libmtp/libmtp/files/4773559/lsusb.txt)
VID=091e 
PID=4cdb

**Garmin tactix® Delta Sapphire Edition** 
https://buy.garmin.com/en-US/US/p/696005

**Comment by msmeissn** [comment]
This is in the libmtp 1.1.17 release, via commit 61809f46

Thanks for the report!
