### ISSUE TITLE
Unkown device

### ISSUE THREAD

**Issue by valioDOTch** [libmtp/libmtp#44]
Half of the time I can connect the video device to my linux laptop, half of the time it fails.

It's reaaaally annoying :'-(

According to the log of gtmp I hereby report the VID/PID along with the device model to the dev team

> Device: FITT360 (see https://fitt360.co.kr/en/ )

> Device 0 (VID=05c6 and PID=901b) is UNKNOWN in libmtp v1.1.13.
> Please report this VID/PID and the device model to the libmtp development team
> PTP_ERROR_IO: failed to open session, trying again after resetting USB interface
> LIBMTP libusb: Attempt to reset device
> LIBMTP PANIC: failed to open session on second attempt
> Detect: Unable to open raw device?
> LIBMTP PANIC: Trying to dump the error stack of a NULL device!

Thank you for your work and your consideration.

**Comment by msmeissn** [comment]
I have added it for next release, hope it will help.

**Comment by valioDOTch** [comment]
Thank you! :-)
