### ISSUE TITLE
Device 0 (VID=091e and PID=4cdb) is UNKNOWN in libmtp v1.1.16.

### ISSUE THREAD

**Issue by stefangweichinger** [libmtp/libmtp#45]
`ID 091e:4cdb Garmin International`

in my case this is a Garmin Fenix 6X Pro smartwatch / multisport watch.

I report this back as I am searching for a way to get this device properly displayed in the software https://github.com/Maproom/qmapshack

If you add that info to `libmtp`, I assume it will take some time to get that change via my distro Fedora.
Please advise if I can somehow manually add that to my system.

Currently the watch gets mounted in Gnome Nautilus, but not via MTP, as it seems?
thanks ...

**Comment by msmeissn** [comment]
should be fixed in commit 61809f46

**Comment by msmeissn** [comment]
and release 1.1.17 :)

**Comment by stefangweichinger** [comment]
Thanks. In my case it's not a "Fenix 6 Sapphire" btw .. but maybe they share the same IDs, I don't know (>20 Fenix 6 models).

**Comment by msmeissn** [comment]
yes, there can be multiple devices with the same ID ... our detection logic only uses the IDs in the end.

**Comment by stefangweichinger** [comment]
Unfortunately not even Fedora Rawhide provides a package for 1.1.17 yet. Is there a way I can get that ID detected in my current system already? Thanks for pointers ...
