### ISSUE TITLE
Device ID for Lenovo Tab 

### ISSUE THREAD

**Issue by ralflr** [libmtp/libmtp#53]
Modell: Lenovo **TB-X704L**

libmtp version: 1.1.17

Device 0 (VID=17ef and PID=7ad0) is UNKNOWN in libmtp v1.1.17.
Please report this VID/PID and the device model to the libmtp development team
error returned by libusb_claim_interface() = -6LIBMTP PANIC: Unable to initialize device
No devices.

**Comment by msmeissn** [comment]
already in git with commit f5ea96b1, will be in next release 1.1.18.
thanks for the report!
