### ISSUE TITLE
problems cross-building for Windows with MXE

### ISSUE THREAD

**Issue by dirkhh** [libmtp/libmtp#59]
I configure libmtp with `libmtp/configure CC=i686-w64-mingw32.shared-gcc --host=i686-w64-mingw32.shared --enable-shared --prefix=/__w/mxe/usr/i686-w64-mingw32.shared`, similar to many other autoconf based libraries that I use.
But when I try to build libmtp I get loads of these errors:
```
/bin/bash ../libtool  --tag=CC   --mode=link i686-w64-mingw32.shared-gcc -I/win/mxe/usr/i686-w64-mingw32.shared/include/libusb-1.0   -g -O2 -Wall -Wmissing-prototypes -no-undefined -export-symbols /__w/libmtp/src/libmtp.sym -version-info 13:0:4 -export-dynamic  -o libmtp.la -rpath /__w/mxe/usr/i686-w64-mingw32.shared/lib libmtp_la-libmtp.lo libmtp_la-unicode.lo libmtp_la-util.lo libmtp_la-playlist-spl.lo libmtp_la-ptp.lo libmtp_la-mtpz.lo libmtp_la-libusb1-glue.lo   -lws2_32 -liconv -lusb-1.0   -lgcrypt 
libtool: link: /__w/mxe/usr/bin/i686-w64-mingw32.shared-nm -B  .libs/libmtp_la-libmtp.o .libs/libmtp_la-unicode.o .libs/libmtp_la-util.o .libs/libmtp_la-playlist-spl.o .libs/libmtp_la-ptp.o .libs/libmtp_la-mtpz.o .libs/libmtp_la-libusb1-glue.o   | sed -n -e 's/^.*[	 ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[	 ][	 ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/\1 _\2 \2/p' | sed '/ __gnu_lto/d' | /bin/sed -e '/^[BCDGRS][ ]/s/.*[ ]\([^ ]*\)/\1 DATA/;s/^.*[ ]__nm__\([^ ]*\)[ ][^ ]*/\1 DATA/;/^I[ ]/d;/^[AITW][ ]/s/.* //' | sort | uniq > .libs/libmtp.exp
libtool: link: if test DEF = "`/bin/sed -n -e 's/^[	 ]*//' -e '/^\(;.*\)*$/d' -e 's/^\(EXPORTS\|LIBRARY\)\([	 ].*\)*$/DEF/p' -e q .libs/libmtp.def`" ; then cp .libs/libmtp.def .libs/libmtp-9.dll.def; else echo EXPORTS > .libs/libmtp-9.dll.def; cat .libs/libmtp.def >> .libs/libmtp-9.dll.def; fi
libtool: link:  i686-w64-mingw32.shared-gcc -shared .libs/libmtp-9.dll.def  .libs/libmtp_la-libmtp.o .libs/libmtp_la-unicode.o .libs/libmtp_la-util.o .libs/libmtp_la-playlist-spl.o .libs/libmtp_la-ptp.o .libs/libmtp_la-mtpz.o .libs/libmtp_la-libusb1-glue.o   -lws2_32 /win/mxe/usr/i686-w64-mingw32.shared/lib/libiconv.dll.a /win/mxe/usr/i686-w64-mingw32.shared/lib/libusb-1.0.dll.a /win/mxe/usr/i686-w64-mingw32.shared/lib/libgcrypt.dll.a -L/win/mxe/usr/i686-w64-mingw32.shared/lib  -g -O2   -o .libs/libmtp-9.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libmtp.dll.a
Warning: resolving _htons by linking to _htons@4
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
Warning: resolving _ntohs by linking to _ntohs@4
Warning: resolving _htonl by linking to _htonl@4
Warning: resolving _ntohl by linking to _ntohl@4
`_htons' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00150.o)
`_ntohs' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00158.o)
`_ntohs' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00158.o)
`_htons' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00150.o)
`_htons' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00150.o)
`_htonl' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00149.o)
`_htonl' referenced in section `.text' of .libs/libmtp_la-ptp.o: defined in discarded section `.text' of /win/mxe/usr/i686-w64-mingw32.shared/lib/libws2_32.a(dtsass00149.o)
```

I'd be curious if anyone knows a fix for that. Googling hasn't really brought me anything that seemed helpful.

**Comment by msmeissn** [comment]
you seem to link agains ws2_32 already where the function is.

Is there a warning about it being not defined before or so?  
can you throw a #include <winsock.h> into gphoto2-endian.h ?

**Comment by dirkhh** [comment]
The compile stage seems to work, it's the link that fails.
But let's pause here for a moment because it seems that this might be an issue that goes away if I update my MXE toolchain to a newer version. Given how long it takes to compile all the libraries that we need (this is all not for a media application, but for Subsurface, an open source dive log), I don't tend to update MXE very often.
I now have a 64bit build (the above was 32bit) of libmtp with MXE (not the latest master, that's broken, but of about six weeks ago). But that version of MXE fails one other component of our app. Oy vey.

In the meantime... entirely unrelated... when I plug the dive computer (Garmin Descent Mk2i) into Windows, Windows appears to grab it and Subsurface can't seem to open it. Is there a magic incantation to make that work? On macOS all I need to do is kill the Android File Transfer app and then Subsurface happily talks to the dive computer. On Linux it works out of the box. On Windows I get LIBMTP panic, unable to initialize device...

**Comment by msmeissn** [comment]
I lack this kind of windows knowledge, sorry.

**Comment by dirkhh** [comment]
No worries. I think I figured it out. Maybe this is something that I should have known (but I never use Windows, either - but oddly my users do). I hadn't installed the special Windows USB drivers that are needed for libusb and therefore libmtp to work. Almost all dive computers implement USB serial (which doesn't need a special driver) or USB storage (ditto). So this was a first for me. Running Zadig and installing `libusbK` did the trick for me.
Would it make sense for me to send a patch for the README that points people in that direction?

To be explicit, I now have libmtp working - with Win64 and with Zadig installed, so I'm closing this issue (and apologize for the noise)
