### ISSUE TITLE
Handling of empty strings as NULL needs documentation

### ISSUE THREAD

**Issue by nh2** [libmtp/libmtp#67]
`libmtp` is somewhat confusing in its uses of empty strings, representing them as NULL pointers also across its public API.

For example,

```c
struct LIBMTP_devicestorage_struct {
  ...
  char *StorageDescription; /**< A brief description of this storage */
```

According to the [MTP spec](https://www.usb.org/document-library/media-transfer-protocol-v11-spec-and-mtp-v11-adopters-agreement) section 5.2.2.7, devices can set `StorageDescription` to be an empty string.

`libmtp` in that case sets `char *StorageDescription` to a `NULL` pointer, not to an empty string `""`.

This is certainly surprising to a use rwith the spec in hand expecting an "empty string", and caused crashes in downstream programs like GVFS that expect `""` (and thus all Linux GUI file managers based on that, when used on devices with empty StorageDescription). I just fixed such an instance [here](https://gitlab.gnome.org/GNOME/gvfs/-/merge_requests/106), and promised there to ask over at libmtp if the use of `NULL` is intentional or grown historically.

For some background on `StorageDescription` specifically, it is extracted in `ptp_unpack_SI()`:

https://github.com/libmtp/libmtp/blob/882ac2972c6479932fc63fb806106f9f65feac1c/src/ptp-pack.c#L598-L602

via via `ptp_unpack_string()` here:

https://github.com/libmtp/libmtp/blob/882ac2972c6479932fc63fb806106f9f65feac1c/src/ptp-pack.c#L130-L137

Whatever the preferred way of representing empty MTP strings in C is, I think it should be documented in the public API.

---

CC @msmeissn as author of commit a06f9c1af83e1c39f29a9f82ee7373c9699743f6 - `change api of ptp_unpack_string to support also unpacking "PTP" empty strings`, which did not change behaviour in this regard but documented:

```
 * PTP strings ... if the size field is:
 * size 0  : "empty string" ... we interpret that as NULL, return 1
```

**Comment by nh2** [comment]
For completeness and googleability of this topic, this mtp tools like `mtp-filetree` show `Storage: (null)` instead of `Storage: `:

```sh
$ examples/mtp-filetree | head
Device 0 (VID=05ca and PID=0368) is a Ricoh Theta V (MTP).
Attempting to connect device(s)
Device: (NULL)
Storage: (null)
```

**Comment by msmeissn** [comment]
Interpretation here is really tricky. 
If its 0 bytes long, should it be "" ? 
It can be 1 bytes long with just a 0 ,.. , would also be "" ?

**Comment by msmeissn** [comment]
hmm. empty string might really refer to ""  :/

**Comment by nh2** [comment]
The way I see it: The MTP spec _defines_ how an empty string is to be represented (with a single byte, `0x00`), completely independent of what C or other language specs say how an empty string is to be represented.

With libmtp you're translating MTP strings to C strings. You can choose how to do that translation, the spec won't tell you what's right or wrong.

I'm arguing that translating empty strings to NULL instead of `""` is wrong/confusing from the _C_ side, not from the MTP side. For example, you can call `strlen("")` but you [cannot](https://stackoverflow.com/questions/5796103/strlen-not-checking-for-null) call `strlen(NULL)`. To C, NULL isn't a string, but `""` is (the 1-byte array containing only the `'\0'` char).

> If its 0 bytes long, should it be "" ?
> It can be 1 bytes long with just a 0 ,.. , would also be "" ?

The answer to both is probably yes; at least when the spec talks about "empty strings", this would be the most obvious translation to C.

The only exception would be when the spec talks about an "optional" string (I don't know if it does that anyhwere), where the empty string, and the string not existing at all, need to be explicitly distinguished. An example of something like this could be some API call `updateOwner(char * name, char * address)`, where passing NULL for the address might mean "do not update the address, keep the current one as is", and passing `""` for the address means to set the address to the empty string.

Could you point me to an example of where 0-bytes long strings exist in the spec, so I can check it out?

**Comment by msmeissn** [comment]
I thought about it, and i think its best to go back to the previous behaviour.

I was not seeing fallout in libgphoto2, as this translates it internally, and never exposes that directly.

**Comment by nh2** [comment]
:+1:
