### ISSUE TITLE
Submit Vendor/Product ID for Mudita Pure phone

### ISSUE THREAD

**Issue by niepiekm** [libmtp/libmtp#72]
Hi, I'd like to add Mudita Pure phone to the list of supported MTP devices

Vendor ID: 3310
Product ID: 0100  

[pure_lsusb.txt](https://github.com/libmtp/libmtp/files/5829086/pure_lsusb.txt)

Prior submission to Sourceforge project:
https://sourceforge.net/p/libmtp/bugs/1895/

**Comment by msmeissn** [comment]
is this android based?

**Comment by niepiekm** [comment]
No, it's a feature phone running a custom firmware based on FreeRTOS, https://github.com/mudita/MuditaOS 

https://mudita.com/products/pure/

**Comment by msmeissn** [comment]
added to git, please check if it works ;)
