### ISSUE TITLE
Device 0 (VID=091e and PID=4cd8) is UNKNOWN in libmtp v1.1.17.

### ISSUE THREAD

**Issue by FrankGNL** [libmtp/libmtp#73]
Another Garmin device that i would to be added
It is a Garmin Fenix 6S Pro

DMESG:
`New USB device found, idVendor=091e, idProduct=4cd8, bcdDevice= 0.01`

Thx

**Comment by msmeissn** [comment]
is in commit fc1c939d
not yet in any release
