### ISSUE TITLE
"Please report this VID/PID and the device model to the libmtp development team"

### ISSUE THREAD

**Issue by MaxMatti** [libmtp/libmtp#75]
```$ mtp-detect
libmtp version: 1.1.18

Listing raw device(s)
Device 0 (VID=0b05 and PID=600f) is UNKNOWN in libmtp v1.1.18.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   0b05:600f @ bus 1, dev 12
Attempting to connect device(s)
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP PANIC: Unable to initialize device
Unable to open raw device 0
OK.
```

That's an Asus ZenPad 10.

**Comment by msmeissn** [comment]
thx for the report, added to git for next release!

**Comment by yotam-medini** [comment]
similar:

Aug 17 23:33:18 zorani kernel: [4932274.324895] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Aug 17 23:33:18 zorani kernel: [4932274.324902] usb 1-2: Product: BLAIR-MTP _SN:9389AEAB
Aug 17 23:33:18 zorani kernel: [4932274.324907] usb 1-2: Manufacturer: SHARP
Aug 17 23:33:18 zorani kernel: [4932274.324913] usb 1-2: SerialNumber: SXILHMA2C0803385
Aug 17 23:33:18 zorani mtp-probe: checking bus 1, device 49: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2"
Aug 17 23:33:18 zorani mtp-probe: bus: 1, device: 49 was an MTP device
Aug 17 23:33:18 zorani mtp-probe: checking bus 1, device 49: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2"
Aug 17 23:33:18 zorani mtp-probe: bus: 1, device: 49 was an MTP device
Aug 17 23:33:24 zorani gvfsd[3922070]: Device 0 (VID=0489 and PID=c030) is UNKNOWN in libmtp v1.1.19.
Aug 17 23:33:24 zorani gvfsd[3922070]: Please report this VID/PID and the device model to the libmtp development team
Aug 17 23:33:24 zorani gvfsd-computer[121798]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by towc** [comment]
garmin venu:
```
libmtp version: 1.1.21

Device 0 (VID=091e and PID=5224) is UNKNOWN in libmtp v1.1.21.
Please report this VID/PID and the device model to the libmtp development team
```

```
Device info:
   Manufacturer: Garmin
   Model: Venu 4 - 41mm
   Device version: 1637
   Serial number: 0000d7ad3df1
   Vendor extension ID: 0x00000006
   Vendor extension description: microsoft.com: 1.0;
   Detected object size: 64 bits
   Extensions:
        microsoft.com: 1.0
```
