### ISSUE TITLE
Device 0 (VID=05c6 and PID=f000) is UNKNOWN in libmtp v1.1.18.

### ISSUE THREAD

**Issue by Nek-12** [libmtp/libmtp#78]
Device 0 (VID=05c6 and PID=f000) is UNKNOWN in libmtp v1.1.18.
Please report this VID/PID and the device model to the libmtp development team
Found 1 device(s):
05c6:f000 @ bus 1, dev 2

Device OnePlus 7Pro OOS 11.0.0.1 Android 11

**Comment by msmeissn** [comment]
thx for the report :)
