### ISSUE TITLE
GetPartialObject bug on Samsung Galaxy devices and possible workaround in libmtp

### ISSUE THREAD

**Issue by cvubrugier** [libmtp/libmtp#8]
While copying more than one thousand pictures from a Samsung Galaxy A3, I observe that several images cannot be retrieved. Copying these images fails with an I/O error after a time-out:

    cp /run/user/1000/gvfs/mtp\:host\=%5Busb%3A001%2C006%5D/Phone/DCIM/OpenCamera/IMG_20180305_115203.jpg /tmp/
    cp: error reading '/run/user/1000/gvfs/mtp:host=%5Busb%3A001%2C006%5D/Phone/DCIM/OpenCamera/IMG_20180305_115203.jpg': Input/output error

With `dd`, I observed that the error occurs while copying the last 500 bytes of the file.

I believe this issue is a bug in Samsung's MTP responder. While we can't fix Samsung's MTP responder which is probably closed source, I think a workaround can be implemented in libmtp.

I reproduced the issue with several Samsung Galaxy devices: A3, A7, and S7.

Description of the bug
----------------------

The bug only happens under the following conditions:
1. the GetPartialObject command is used to read the file
2. the GetPartialObject offset is `size - (N * 512) + 500` bytes with `N` being an integer
3. the GetPartialObject request reaches the end of the file

In practice, most clients of libmtp use a block size which is a power of 2, usually a multiple of 512 bytes. So the offset of a GetPartialObject request is likely to be a multiple of 512 bytes. This condition combined with condition 2 makes the bug occur when `(size % 512) == 500` with a probability of 1/512.

When the bug happens, the Samsung Galaxy device does not return the requested data and the GetPartialObject command fails after a time-out.

How to reproduce the issue
--------------------------

I have written a [tool to help reproduce the issue](https://github.com/cvubrugier/mtp-galaxy-bug). The repository contains a Python script to identify files from a Samsung Galaxy device that may cause the error and a C program that uses GetPartialObject to read the end of the file and observe the time-out error.

Possible workaround
-------------------

I will propose a patch that implements a workaround. The idea is to add some code for GetPartialObject in order to identify the faulty condition for Samsung Galaxy devices and read one less byte, forcing
the caller to request an additional read to get the last byte.

**Comment by msmeissn** [comment]
can you try settingf the flag DEVICE_FLAG_NO_ZERO_READS , this implements this already

**Comment by msmeissn** [comment]
for th4e samsung de vice you have in music-players.h

**Comment by cvubrugier** [comment]
@msmeissn wrote:
> Can you try setting the flag `DEVICE_FLAG_NO_ZERO_READS` for the Samsung device you have in `music-players.h`?

Thank you for your prompt reply!
Setting `DEVICE_FLAG_NO_ZERO_READS` does not fix the issue. I still experience an error after a time-out (after one minute).

**Comment by msmeissn** [comment]
perhaps @philipl has an idea.

**Comment by cvubrugier** [comment]
I don't understand what is magic about the `(size % 512) == 500` condition that causes the Samsung Galaxy device not to send a MTP reply. Maybe `PTP_USB_BULK_HDR_LEN` being 12 bytes added to 500 bytes causes a special condition.

**Comment by cvubrugier** [comment]
I performed more tests and the `size % 512 == 500` condition does not capture all the situations where a Samsung Galaxy device does not respond. Computing a start offset which is `size - 500` and performing a GetPartialObject request starting at this offset causes a time-out as well. I will update my first comment to reflect that and modify my reproducer.

**Comment by msmeissn** [comment]
There is a lowlevel USB bulk transfer magic, where the last transfer is signaled by a 0 buyte transfer. This is apparently tricky to understand and get right.

512 byte is the USB 2.0 packetsize, 12 byte is the PTP data header size, so 500 is a magic bytecount there.

**Comment by cvubrugier** [comment]
I added `LIBMTP_Set_Debug(0xFF)` to the reproducer and captured the output. I see no difference in the log output after adding the `DEVICE_FLAG_NO_ZERO_READS` flag for Samsung Galaxy devices. Here is the part of the output before calling `LIBMTP_GetPartialObject()`:

[libmtp-normal.log](https://github.com/libmtp/libmtp/files/1872337/libmtp-normal.log)

**Comment by philipl** [comment]
Can you upload an mtp-detect report? A modern android phone (This is a 2017 model right?) should be using the AOSP mtp stack, but Samsung certainly had their own weird buggy one back in the day, and maybe this is still being used.

**Comment by cvubrugier** [comment]
The phone is a Samsung Galaxy A3 (2017). The software information section on the phone displays:
* Android version: 7.0
* Samsung experience version: 8.1

Here is the `mtp-detect` report: [mtp-detect-samsung-galaxy-A3.txt](https://github.com/libmtp/libmtp/files/1888750/mtp-detect-samsung-galaxy-A3.txt)

**Comment by philipl** [comment]
Yeah - what I figured. Their stack has always been garbage. I think a new bug flag like your patch implements is what will be required. If I'm reading DEVICE_FLAG_NO_ZERO_READS correctly, that's responding to a different behaviour where the device sends an extra byte in situations where a zero read would occur. In our case, the device freaks out when asked to transfer those last bytes and we never reach the point of dealing with a zero read.
 
@msmeissn I think a new flag is the only viable approach, either the patch here or something like it. If I had a device I could do some experiments but the situation seems believable enough.

**Comment by philipl** [comment]
I'm pretty sure gphoto2 doesn't use `GetPartialObject()` anywhere - so it's succeeding because it does `GetObject()`.

This brings me to the other angle. Up until now we've discussed the bug. We haven't discussed why you're using `dd`.

If your goal is to copy files from your phone to your computer from the command line, you should use 'gio copy' to do it. That will use the gvfs `pull()` operation which is implemented in terms of `GetObject()` in gvfsd-mtp. It's also what Nautilus calls when you do copy operations. That will avoid the problem completely.

All that said I think you either implement the workaround or you blacklist GetPartialObject() on Samsung devices and don't use it (in which case your dd call would fail completely because reads through fuse would not be supported)

**Comment by philipl** [comment]
I think the patch logic is out of date with respect to your findings, isn't it? The problem triggers if your offset is (filesize - 500) and then you try and your count is >= 500 right?

**Comment by cvubrugier** [comment]
Yes, I will update the patch.

**Comment by msmeissn** [comment]
I approved the pull request.
