### ISSUE TITLE
Use a dedicated libusb context instead of the default one

### ISSUE THREAD

**Issue by striker-vlabs** [libmtp/libmtp#80]
I've been trying to use libusb hotplug functionality to detect new mtp device being connected. 
and ran into issues since libmtp use the default context, which according to the libusb doc shouldn't be use when in the same process multiple libraries are using libusb.

https://libusb.sourceforge.io/api-1.0/libusb_contexts.html

Also take notes that `libusb_exit()` which is used to cleanup the library is never called by libmtp

**Comment by msmeissn** [comment]
i just added it to what we call. Also currently a global variable, which makes thread usage hard.

i need to see how to hook in the libusb_exit.
