### ISSUE TITLE
libmtp 1.1.19 lists empty device

### ISSUE THREAD

**Issue by svonohr** [libmtp/libmtp#83]
After recently upgrading to libmtp 1.1.19 the KDE file manager does not list any files or folders on the device. Downgrading back to 1.1.18 fixes the issue, so this seems to be a recent change. I need help narrowing down the problem, so this can be fixed.

I tried running the mtp tools and `mtp-detect` and `mtp-connect` still seem to work with 1.1.19. Running any of the other tools, e.g. `mtp-newfolder`, seem to do a full device listing before doing anything. This did not finish with my Android phone despite leaving it running for several minutes. However the debug output shows that even with 1.1.19 it's listing files on my device. So this might be specific to the KDE mtp plugin.

Are there any other tools/diagnostic I can run to help narrow this down?

**Comment by msmeissn** [comment]
which device is reported by mtp-detect ?

**Comment by svonohr** [comment]
Output of mtp-detect:
```
libmtp version: 1.1.19

Listing raw device(s)
Device 0 (VID=18d1 and PID=4ee1) is a Google Inc Nexus/Pixel (MTP).
   Found 1 device(s):
   Google Inc: Nexus/Pixel (MTP) (18d1:4ee1) @ bus 3, dev 13
Attempting to connect device(s)
Android device detected, assigning default bug flags
```
It's a Google Nexus 5X to be specific.
Full mtp-detect output: [mtp-detect.log](https://github.com/libmtp/libmtp/files/7271223/mtp-detect.log)

**Comment by svonohr** [comment]
Shortly after opening this issue, it started working again with 1.1.19. Not sure what caused the issue.
