### ISSUE TITLE
VID=0fce and PID=020d is UNKNOWN in libmtp v1.1.17

### ISSUE THREAD

**Issue by uvwild** [libmtp/libmtp#86]
journalctl says

Please report this VID/PID and the device model to the libmtp development team

on Ubuntu 20.04.3

on SONY XQ BT52

it works for a moment but then disconnects
gvfsd-computer[16892]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by msmeissn** [comment]
id is in the 1.1.19 release, thanks for the report!
