### ISSUE TITLE
Device 0 (VID=0a9d and PID=ff40) is UNKNOWN in libmtp v1.1.18.

### ISSUE THREAD

**Issue by johannbg** [libmtp/libmtp#90]
>Device 0 (VID=0a9d and PID=ff40) is UNKNOWN in libmtp v1.1.18.

Device model: Xiaomi MI 9 M1902F1G

**Comment by msmeissn** [comment]
we had the ff40 id twice already, but we can have more instances of it. it will just detect the first in the list usually.
