### ISSUE TITLE
(VID=2672 and PID=004d) is UNKNOWN in libmtp v1.1.17

### ISSUE THREAD

**Issue by ultradian** [libmtp/libmtp#97]
Was trying to use mtp with a Hero 9 Black and got the message 
```
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   2672:004d @ bus 1, dev 23
Attempting to connect device(s)
error returned by libusb_claim_interface() = -6LIBMTP PANIC: Unable to initialize device
Unable to open raw device
```
So, reporting. Let me know if you need other info.

**Comment by msmeissn** [comment]
id is listed in the 1.1.19 release, thanks for the report!

the -6 means "Busy", it is already being blocked by GVFS or similar tooling.
